### ISSUE TITLE
Many actions may be missing in DPS/HPS statistics under certain conditions

### ISSUE THREAD

**Issue by TundraWork** [TundraWork/FFXIV_ACT_Plugin_CN#5]
Actions including many healing abilities, as well some AOEs, may be missing in DPS/HPS statistics under some conditions which we have no conclusion.

We are investigating this issue without any bright ideas.

Fixes may come late, or worse, never come.

**Comment by raimirow** [comment]
2.20.7.1版本解析出来的logs里面没有01:、14:、15:、16:这些ACT日志行。
logs里时间每隔2到3秒，就会有类似这样的错误信息
|TCPDecoder: >2 sec since last processed packet, resetting stream.|a1350bda33eb024a8ccca3fa61fc3a82
251|2020-07-22T01:01:08.2658146+08:00|TCPDecoder: Missing Sequence # [2551793878], Dropping packet with sequence # [2551796621].|1897bd5ebb280289059e4181762c5dbc
251|2020-07-22T01:01:08.2658146+08:00|TCPDecoder: Missing Sequence # [2551793878], Dropping packet with sequence # [2551795870].|e9d247ed57d68398818dbe6f572ec777

**Comment by TundraWork** [comment]
> 2.20.7.1版本解析出来的logs里面没有01:、14:、15:、16:这些ACT日志行。
> logs里时间每隔2到3秒，就会有类似这样的错误信息
> |TCPDecoder: >2 sec since last processed packet, resetting stream.|a1350bda33eb024a8ccca3fa61fc3a82
> 251|2020-07-22T01:01:08.2658146+08:00|TCPDecoder: Missing Sequence # [2551793878], Dropping packet with sequence # [2551796621].|1897bd5ebb280289059e4181762c5dbc
> 251|2020-07-22T01:01:08.2658146+08:00|TCPDecoder: Missing Sequence # [2551793878], Dropping packet with sequence # [2551795870].|e9d247ed57d68398818dbe6f572ec777

Thanks for the details, we have noticed this and continue investigating.

**Comment by TundraWork** [comment]
Should be fixed in https://github.com/TundraWork/FFXIV_ACT_Plugin_CN/releases/tag/2.20.7.2
